#!/bin/bash

# I want to survive the robot apocalypse
alias please=sudo

# git aliases for the super lazy
alias gall="git commit -am"
alias gps="git push"
alias gpl="git pull --rebase --autostash"
alias gc="git commit"
alias gl="git log --oneline"
alias gs="git status"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ls aliases
alias ll='ls -alF'
alias la="ls -lahF"
alias l='ls -CF'
# List only directories
alias lsd="ls -lhF | grep --color=never '^d'"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# IP addresses
alias pubip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="sudo ifconfig | grep -Eo 'inet (addr:)?([0-9]*\\.){3}[0-9]*' | grep -Eo '([0-9]*\\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ips="sudo ifconfig -a | grep -o 'inet6\\? \\(addr:\\)\\?\\s\\?\\(\\(\\([0-9]\\+\\.\\)\\{3\\}[0-9]\\+\\)\\|[a-fA-F0-9:]\\+\\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# copy working directory
alias cwd='pwd | tr -d "\r\n" | xclip -selection clipboard'

# Copy my public key to clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | xclip -selection clipboard | echo '=> Public key copied to clipboard.'"

alias untar='tar xvf'
alias gr='grep -r'
alias mount='mount | column -t'

# kubernetes
alias kuberestarts="kubectl get pods --all-namespaces --sort-by='.status.containerStatuses[0].restartCount'"
alias kubenotrunning="kubectl get pods --all-namespaces |grep -v Running"

# Ruby development
alias be="bundle exec"

# Go, list packages that can be upgraded
alias goupgrade="go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all 2> /dev/null"

# Python
# clear pycache if tox is failing
alias pycache_clear="find . \( -name '__pycache__' -or -name '*.pyc' \) -delete"

# Oda specific
alias klipy="/Users/martapaciorkowska/kolonialno/klipy/.venv/bin/python -m klipy"
