#!/bin/bash

#
# variables
#

export GOBIN=$HOME/go/bin
export GOPATH=$HOME/go

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

#
# path
#

export PATH=$PATH:/usr/local/go/bin:$GOBIN

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
